Vagrant.configure("2") do |config|
  config.vm.box = "cbednarski/ubuntu-1604"
  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 2
  end
  config.vm.provision "shell", path: "scripts/packer.sh"
  config.vm.provision "shell", path: "scripts/docker.sh"
end
